queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - label~=merge-queue|auto-merge|dependencies
    merge_conditions:
      - check-success=buildbot/nix-build
    merge_method: rebase

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
